server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersDB
    username: rigo
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
