server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/staging_user_db
    username: rigo
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect